### PR TITLE
Tidy table markup.

### LINKED ISSUE #40: Remove unnecessary cellbgcolor
For example, the tables in section 3.

### PR DESCRIPTION
**Pull request by rhattersley**
Get rid of unnecessary cellbgcolor markup, and generally tidy up and simplify.

Closes #40.

### CODE REVIEW

**Comment by marqh** [comment]
neat, loads less code for the same output, definitely an improvement

i've made merge conflicts by merging other PRs so please may you rebase?

**Comment by rhattersley** [comment]
> i've made merge conflicts by merging other PRs so please may you rebase? 

It's a problem I'm happy to have! :wink:

**Comment by rhattersley** [comment]
Rebased.

**Comment by marqh** [comment]
thank you

**Pull request merged**
