### PR TITLE
Add lists of tables and examples.

### LINKED ISSUE #25: List of tables/examples
The "List of Tables" and "List of Examples" are missing. In the original they occur immediately after the "Table of Contents".

### PR DESCRIPTION
**Pull request by rhattersley**
Closes #25.

### CODE REVIEW

**Comment by marqh** [comment]
I think this is correct, the build is fine and the examples and tables list fine
there are now conflicts, so a rebase, please

**Comment by rhattersley** [comment]
Rebased.

**Comment by marqh** [comment]
excellent, getting awfully close ...

**Comment by rhattersley** [comment]
> getting awfully close ...

Yeah, shame I moved the goalposts with #46. :wink:

**Pull request merged**
